<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>card_Banner_left</name>
   <tag></tag>
   <elementGuidId>013a16bb-d1af-42c6-a702-fba35d094f7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section/section/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.promo.left.bg-success.rounded-end.flex-grow-1.align-self-center.d-none.d-lg-block</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7b33fd9a-4624-464c-944f-efe8362cd3b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>promo left bg-success rounded-end flex-grow-1 align-self-center d-none d-lg-block</value>
      <webElementGuid>ca6228fe-4f35-4e3f-9200-02d8b3fd2cb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;pt-5 mt-5&quot;]/section[@class=&quot;mt-lg-5 mb-5 w-100 d-flex gap-lg-5&quot;]/div[@class=&quot;promo left bg-success rounded-end flex-grow-1 align-self-center d-none d-lg-block&quot;]</value>
      <webElementGuid>1689caa4-e33a-4c3f-9eb6-42073fbb6b97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/section/div</value>
      <webElementGuid>bfff8a4d-35a8-45c3-a555-5285b9fa21a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
