<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_SecondHand_titleLoginpage</name>
   <tag></tag>
   <elementGuidId>4b533d1e-8d5d-429a-b8fc-94c40c9ed930</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.brand</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>82ef8609-651c-4a1f-b6eb-ba5618282bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>brand</value>
      <webElementGuid>429762f4-5ada-4b48-aa94-775aff320185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SecondHand.</value>
      <webElementGuid>36a2a41e-2bae-4364-a625-3ec0447e5d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6 d-none d-sm-block position-relative&quot;]/h2[@class=&quot;brand&quot;]</value>
      <webElementGuid>c528bb7e-6f47-42a2-add9-79a21850fd52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/h2</value>
      <webElementGuid>383c6905-6517-4941-9807-6d3b7412ed0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[1]/preceding::h2[1]</value>
      <webElementGuid>9d0c6b82-0769-43d9-a23d-b1acfc8e9445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::h2[2]</value>
      <webElementGuid>41407496-0cdc-44d2-8d5b-34fb109b96a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Second']/parent::*</value>
      <webElementGuid>a3f46269-c773-4729-97f4-44b9c09e053d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>c7f66429-6518-43f6-b9b8-10b08b60e668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'SecondHand.' or . = 'SecondHand.')]</value>
      <webElementGuid>d887ce2a-d597-4ae2-99cf-c315fad634fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
