<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>card_Banner_right</name>
   <tag></tag>
   <elementGuidId>8c233397-4b7e-41e8-8541-da35dadacb84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.promo.right.bg-info.rounded-start.flex-grow-1.align-self-center.d-none.d-lg-block</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5ec52e0a-b38b-4045-bc0b-bc7efbfbf1ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>promo right bg-info rounded-start flex-grow-1 align-self-center d-none d-lg-block</value>
      <webElementGuid>d9b38d91-c210-4774-a52f-41f7057e8cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;pt-5 mt-5&quot;]/section[@class=&quot;mt-lg-5 mb-5 w-100 d-flex gap-lg-5&quot;]/div[@class=&quot;promo right bg-info rounded-start flex-grow-1 align-self-center d-none d-lg-block&quot;]</value>
      <webElementGuid>74846015-788d-41d3-82fe-01924cdcd1a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]</value>
      <webElementGuid>e80667ae-b8ae-4781-8120-09dab4080689</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
