<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hlink_Previous</name>
   <tag></tag>
   <elementGuidId>faaae669-32d4-4d49-ad19-f0a9759a7a48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='products']/div[11]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.previous_page.disabled</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c93b23f4-e5f1-44cd-ab75-88ec3fe66c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>previous_page disabled</value>
      <webElementGuid>4caaa309-7d56-4725-ad0f-d7b3085f9599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8aa3df08-164b-4c02-94dd-48b57cc7a143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>← Previous</value>
      <webElementGuid>1e16b0a0-d9fa-4762-ba78-83dc0d452a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;products&quot;)/div[@class=&quot;d-flex gap-4 align-items-center justify-content-center my-5&quot;]/span[@class=&quot;previous_page disabled&quot;]</value>
      <webElementGuid>f5c06259-6f29-4c9e-bc36-f168fbec9634</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='products']/div[11]/span</value>
      <webElementGuid>e9ec0dac-7868-404c-8577-cfaec2036cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 90.000.000'])[1]/following::span[1]</value>
      <webElementGuid>721de693-91bc-4403-998b-4b15d342c38d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='laptop'])[1]/following::span[1]</value>
      <webElementGuid>7a2c95ab-6a5f-40be-961b-57fd3416c06a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next →'])[1]/preceding::span[1]</value>
      <webElementGuid>39d44fbe-708c-4c86-8808-4eb94d36bebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jual'])[1]/preceding::span[1]</value>
      <webElementGuid>474499c8-8b1c-4ebd-aadf-08fe6c3b2ffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='← Previous']/parent::*</value>
      <webElementGuid>fd8dbdc0-0a91-48b0-9194-561c4464308b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/span</value>
      <webElementGuid>49b8c379-f6bd-4259-9920-a8f4282d3d1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '← Previous' or . = '← Previous')]</value>
      <webElementGuid>6e40cab1-a997-46cc-9545-ca91193cfe92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
